"""Shared formatting helpers for the code generators."""

from __future__ import annotations

import datetime as _dt

import numpy as np

from ..core.design import FilterDesign

__all__ = [
    "format_floats",
    "format_complex",
    "format_ints",
    "spec_comment",
    "timestamp",
]

#: Marker every generated file carries, so it is obvious where it came from.
TOOL_NAME = "filter_engine"


def timestamp() -> str:
    return _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def format_floats(
    values: np.ndarray, per_line: int = 4, indent: str = "    "
) -> str:
    """Format floats as Python literals, wrapped across lines.

    ``repr`` gives the shortest string that round-trips exactly, so the taps
    in the generated file are bit-identical to the ones analysed here.
    """
    items = [repr(float(v)) for v in np.asarray(values).ravel()]
    return _wrap(items, per_line, indent)


def format_complex(
    values: np.ndarray, per_line: int = 2, indent: str = "    "
) -> str:
    """Format complex taps as Python literals, wrapped across lines.

    Emitted as ``complex(re, im)`` rather than ``(re+imj)``: the constructor
    round-trips exactly and stays readable when the imaginary part is
    negative or written in exponential form.
    """
    items = [
        f"complex({float(v.real)!r}, {float(v.imag)!r})"
        for v in np.asarray(values).ravel()
    ]
    return _wrap(items, per_line, indent)


def format_ints(values: np.ndarray, per_line: int = 8, indent: str = "    ") -> str:
    items = [str(int(v)) for v in np.asarray(values).ravel()]
    return _wrap(items, per_line, indent)


def _wrap(items: list[str], per_line: int, indent: str) -> str:
    lines = []
    for i in range(0, len(items), per_line):
        chunk = ", ".join(items[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def spec_comment(fd: FilterDesign, prefix: str = "# ") -> str:
    """A comment block describing how the filter was specified.

    Every generated file leads with this.  Coefficients on their own are
    unmaintainable -- six months later nobody remembers whether 0.1 dB of
    ripple was a requirement or a guess -- so the intent travels with them.
    """
    s = fd.spec
    lines = [
        f"Generated by {TOOL_NAME} on {timestamp()}",
        "",
        f"Name:            {s.name}",
        f"Response:        {s.response.value}",
        f"Family:          {s.family.value.upper()}",
        f"Design method:   {s.method}",
        f"Sample rate:     {s.sample_rate:,.6g} Hz  (Nyquist {s.nyquist:,.6g} Hz)",
    ]

    if s.response.value == "matched_lfm":
        lines.append(f"Pulse width:     {s.pulse_width_s * 1e6:,.6g} us")
        lines.append(f"Chirp bandwidth: {s.chirp_bandwidth_hz / 1e6:,.6g} MHz")
        lines.append(f"Sweep:           {'down' if s.down_chirp else 'up'}")
        lines.append(f"Time-bandwidth:  {s.time_bandwidth_product:,.0f}")
        lines.append(f"Range res:       {s.range_resolution_m:,.4g} m")
        lines.append(f"Weighting:       {s.window}")
        if s.window == "taylor":
            lines.append(f"  Taylor SLL:    {s.taylor_sll_db:g} dB")
            lines.append(f"  Taylor nbar:   {s.taylor_nbar}")
        elif s.window == "chebwin":
            lines.append(f"  Chebyshev:     {s.cheb_atten_db:g} dB")
        lines.append("Coefficients:    complex (I/Q)")
    elif s.response.value == "mti_canceller":
        lines.append(f"Pulses:          {s.mti_pulses}")
        lines.append(f"PRI:             {s.pri_s * 1e6:,.6g} us "
                     f"({s.prf_hz:,.6g} Hz PRF)")
        lines.append(f"Carrier:         {s.radar_carrier_hz / 1e9:,.4g} GHz")
        lines.append(f"Blind speeds:    every {s.blind_speed_ms:,.4g} m/s")
        lines.append("Note:            runs in slow time, one sample per PRI")
    elif s.response.is_pulse_shaping:
        lines.append(f"Symbol rate:     {s.symbol_rate:,.6g} Hz")
        lines.append(f"Samples/symbol:  {s.samples_per_symbol:.6g}")
        if s.response.value.endswith("raised_cosine"):
            lines.append(f"Roll-off:        {s.rolloff:g}")
        else:
            lines.append(f"BT product:      {s.bt:g}")
        lines.append(f"Span:            {s.span_symbols} symbols")
        lines.append(f"Normalisation:   {s.normalisation}")
    elif s.response.value == "differentiator":
        lines.append(f"Band edge:       {s.f_high:,.6g} Hz")
    else:
        if s.response.is_multiband:
            lines.append(f"Band edges:      {s.f_low:,.6g} - {s.f_high:,.6g} Hz")
        else:
            lines.append(f"Cutoff:          {s.f_low:,.6g} Hz")
        if s.response.value != "hilbert":
            lines.append(f"Transition:      {s.transition_width:,.6g} Hz")
            lines.append(f"Passband ripple: {s.passband_ripple_db:g} dB")
            lines.append(f"Stopband atten:  {s.stopband_atten_db:g} dB")
        if s.family.value == "fir" and s.method == "window":
            lines.append(f"Window:          {s.window}")

    if fd.is_fir:
        lines.append(f"Taps:            {fd.num_taps}")
        lines.append(f"Group delay:     {(fd.num_taps - 1) / 2.0:g} samples")
    else:
        lines.append(f"Order:           {fd.order}")
        lines.append(f"Sections:        {fd.num_sections}")

    if s.gain != 1.0:
        lines.append(f"Gain:            {s.gain:g}")
    if s.notes:
        lines.append(f"Notes:           {s.notes}")

    if fd.notes:
        lines.append("")
        lines.append("Design notes:")
        lines.extend(f"  - {n}" for n in fd.notes)

    return "\n".join(f"{prefix}{line}".rstrip() for line in lines)
