"""Generate a self-contained Python module for a design.

The output depends only on numpy and scipy.  It carries the coefficients as
literals *and* the call that produced them, so the file works as a drop-in
and stays auditable: anyone can re-run the design call and check it against
the stored taps.
"""

from __future__ import annotations

from ..core.design import FilterDesign
from ..core.spec import FilterFamily, FirMethod, Response
from ._common import format_complex, format_floats, spec_comment

__all__ = ["generate"]


def generate(fd: FilterDesign, class_name: str | None = None) -> str:
    """Return the source of a standalone Python module implementing ``fd``."""
    spec = fd.spec
    name = class_name or _class_name(spec.name)

    parts = [
        '"""',
        spec_comment(fd, prefix=""),
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import numpy as np",
        "from scipy import signal",
        "",
        "",
        f"SAMPLE_RATE = {spec.sample_rate!r}  # Hz",
        "",
    ]

    if fd.is_fir:
        parts.extend(_fir_body(fd, name))
    else:
        parts.extend(_iir_body(fd, name))

    parts.extend(_main_block(fd, name))
    return "\n".join(parts) + "\n"


# --------------------------------------------------------------------------
def _class_name(raw: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in raw).strip("_")
    if not cleaned:
        cleaned = "filter"
    if cleaned[0].isdigit():
        cleaned = f"f_{cleaned}"
    return "".join(part.capitalize() for part in cleaned.split("_") if part)


def _fir_body(fd: FilterDesign, name: str) -> list[str]:
    redesign = _redesign_call(fd)
    if fd.is_complex:
        header = [
            f"#: {fd.num_taps} complex (I/Q) FIR taps.",
            "#:",
            "#: Complex because a matched filter for a complex-baseband chirp",
            "#: has to be: real taps cannot tell an up-sweep from its mirror",
            "#: image, and the compressed pulse would fold on top of itself.",
            "TAPS = np.array([",
            format_complex(fd.b),
            "])",
        ]
    else:
        header = [
            f"#: {fd.num_taps} FIR taps.",
            "TAPS = np.array([",
            format_floats(fd.b),
            "])",
        ]
    lines = [
        *header,
        "",
        "",
        "def design_taps() -> np.ndarray:",
        '    """Recompute the taps from the original specification.',
        "",
        "    Kept alongside the stored TAPS so the design can be verified or",
        "    retuned without going back to the GUI. It should reproduce TAPS",
        "    exactly -- run this module directly to check.",
        '    """',
    ]
    if redesign is None:
        lines.append(
            "    # This response has no single scipy call; the taps above were"
        )
        lines.append("    # generated by filter_engine's own tap generator.")
        lines.append("    return TAPS.copy()")
    else:
        lines.extend(f"    {line}" for line in redesign)
    lines.extend(
        [
            "",
            "",
            f"class {name}:",
            f'    """Streaming FIR filter ({fd.num_taps} taps).',
            "",
            "    State is carried between calls, so feeding successive blocks",
            "    gives the same result as filtering the whole stream at once.",
            '    """',
            "",
            "    def __init__(self, taps: np.ndarray | None = None) -> None:",
            "        self.taps = np.asarray(TAPS if taps is None else taps, dtype=float)",
            "        self.reset()",
            "",
            "    def reset(self) -> None:",
            '        """Clear the filter state."""',
            "        self._zi = np.zeros(self.taps.size - 1)",
            "",
            "    def __call__(self, x: np.ndarray) -> np.ndarray:",
            '        """Filter one block, carrying state across calls."""',
            "        x = np.asarray(x)",
            "        if np.iscomplexobj(x) and not np.iscomplexobj(self._zi):",
            "            self._zi = self._zi.astype(complex)",
            "        y, self._zi = signal.lfilter(self.taps, [1.0], x, zi=self._zi)",
            "        return y",
            "",
            "    def filter_block(self, x: np.ndarray) -> np.ndarray:",
            '        """Filter ``x`` as a one-off, ignoring and leaving state untouched."""',
            "        return signal.lfilter(self.taps, [1.0], np.asarray(x))",
            "",
            "    @property",
            "    def group_delay_samples(self) -> float:",
            '        """Delay through the filter, in samples."""',
            "        return (self.taps.size - 1) / 2.0",
            "",
        ]
    )
    return lines


def _iir_body(fd: FilterDesign, name: str) -> list[str]:
    assert fd.sos is not None
    rows = []
    for section in fd.sos:
        values = ", ".join(repr(float(v)) for v in section)
        rows.append(f"    [{values}],")

    lines = [
        f"#: {fd.num_sections} second-order sections (order {fd.order}).",
        "#: Each row is [b0, b1, b2, a0, a1, a2].",
        "#:",
        "#: Second-order sections rather than a single (b, a): an expanded",
        f"#: order-{fd.order} polynomial loses so much precision that the filter",
        "#: can come out unstable. Always implement the cascade.",
        "SOS = np.array([",
        *rows,
        "])",
        "",
        "",
        "def design_sos() -> np.ndarray:",
        '    """Recompute the sections from the original specification."""',
    ]
    redesign = _redesign_call(fd)
    if redesign is None:
        lines.append("    return SOS.copy()")
    else:
        lines.extend(f"    {line}" for line in redesign)

    lines.extend(
        [
            "",
            "",
            f"class {name}:",
            f'    """Streaming IIR filter (order {fd.order}, '
            f'{fd.num_sections} biquads)."""',
            "",
            "    def __init__(self, sos: np.ndarray | None = None) -> None:",
            "        self.sos = np.asarray(SOS if sos is None else sos, dtype=float)",
            "        self.reset()",
            "",
            "    def reset(self) -> None:",
            '        """Clear the filter state."""',
            "        self._zi = np.zeros((self.sos.shape[0], 2))",
            "",
            "    def __call__(self, x: np.ndarray) -> np.ndarray:",
            '        """Filter one block, carrying state across calls."""',
            "        x = np.asarray(x)",
            "        if np.iscomplexobj(x) and not np.iscomplexobj(self._zi):",
            "            self._zi = self._zi.astype(complex)",
            "        y, self._zi = signal.sosfilt(self.sos, x, zi=self._zi)",
            "        return y",
            "",
            "    def filter_block(self, x: np.ndarray) -> np.ndarray:",
            '        """Filter ``x`` as a one-off, leaving state untouched."""',
            "        return signal.sosfilt(self.sos, np.asarray(x))",
            "",
            "    def filtfilt(self, x: np.ndarray) -> np.ndarray:",
            '        """Zero-phase filtering by running forwards then backwards.',
            "",
            "        Doubles the attenuation and removes the phase distortion,",
            "        at the cost of needing the whole signal up front -- offline",
            "        only, never in a live receive path.",
            '        """',
            "        return signal.sosfiltfilt(self.sos, np.asarray(x))",
            "",
            "    @property",
            "    def is_stable(self) -> bool:",
            '        """True when every pole is inside the unit circle."""',
            "        _z, p, _k = signal.sos2zpk(self.sos)",
            "        return bool(np.all(np.abs(p) < 1.0))",
            "",
        ]
    )
    return lines


def _redesign_call(fd: FilterDesign) -> list[str] | None:
    """The scipy call that reproduces this design, as source lines."""
    s = fd.spec
    fs = s.sample_rate

    if s.response.is_radar:
        return _radar_redesign_call(fd)

    if s.response.is_pulse_shaping:
        return None  # generated by our own firdes-style code

    if s.family is FilterFamily.IIR:
        if fd.prototype_order is None or fd.critical_freqs is None:
            return None
        kwargs = [
            # The prototype order and the realised critical frequencies, not
            # the requested band edges -- see FilterDesign.prototype_order.
            f"{fd.prototype_order}",
            repr(fd.critical_freqs),
            f"btype={s.response.value!r}",
            f"ftype={s.iir_method.value!r}",
            'output="sos"',
            f"fs={fs!r}",
        ]
        if s.iir_method.value in ("cheby1", "ellip"):
            kwargs.append(f"rp={s.passband_ripple_db!r}")
        if s.iir_method.value in ("cheby2", "ellip"):
            kwargs.append(f"rs={s.stopband_atten_db!r}")
        body = ",\n        ".join(kwargs)
        call = f"signal.iirfilter(\n        {body},\n    )"
        if s.gain == 1.0:
            return [f"return {call}"]
        # The gain rides on the first section's numerator, which scales the
        # cascade without moving any pole.
        return [
            f"sos = {call}",
            f"sos[0, 0:3] *= {s.gain!r}",
            "return sos",
        ]

    if s.response is Response.HILBERT:
        return [
            "return signal.remez(",
            f"    {fd.num_taps}, [{s.f_low!r}, {s.f_high!r}], [{s.gain!r}],",
            f'    type="hilbert", fs={fs!r},',
            ")",
        ]
    if s.response is Response.DIFFERENTIATOR:
        return [
            "return signal.remez(",
            f"    {fd.num_taps}, [0.0, {s.f_high!r}], [{s.gain / fs!r}],",
            f'    type="differentiator", fs={fs!r},',
            ")",
        ]

    if s.fir_method is FirMethod.WINDOW:
        cutoff = (
            f"[{s.f_low!r}, {s.f_high!r}]"
            if s.response.is_multiband
            else f"{s.f_low!r}"
        )
        if s.window == "kaiser":
            window = f'("kaiser", {_kaiser_beta(s)!r})'
        else:
            window = repr(s.window)
        scale = "" if s.gain == 1.0 else f" * {s.gain!r}"
        return [
            "return signal.firwin(",
            f"    {fd.num_taps}, {cutoff}, window={window},",
            f"    pass_zero={s.response.value!r}, scale=True, fs={fs!r},",
            f"){scale}",
        ]

    if s.fir_method in (FirMethod.REMEZ, FirMethod.FIRLS):
        from ..core.design import _band_edges

        bands, desired, weights = _band_edges(s)
        if s.fir_method is FirMethod.REMEZ:
            return [
                "return signal.remez(",
                f"    {fd.num_taps}, {bands!r}, {desired!r},",
                f"    weight={weights!r}, fs={fs!r},",
                ")",
            ]
        # firls wants the desired level at each band edge, not once per band.
        desired_edges = [value for value in desired for _ in range(2)]
        return [
            "return signal.firls(",
            f"    {fd.num_taps}, {bands!r}, {desired_edges!r},",
            f"    weight={weights!r}, fs={fs!r},",
            ")",
        ]

    return None  # firwin2 rebuilds a frequency grid; not worth reconstructing


def _window_expression(spec, length: str) -> str:
    """The scipy call that rebuilds this design's weighting window.

    Must match :func:`filter_engine.core.radar.weighting_window` exactly, or
    the emitted ``design_taps()`` will disagree with the emitted ``TAPS``.
    """
    if spec.window == "taylor":
        return (
            f"signal.windows.taylor({length}, nbar={spec.taylor_nbar}, "
            f"sll={abs(spec.taylor_sll_db)!r}, norm=True, sym=True)"
        )
    if spec.window == "chebwin":
        return (
            f"signal.windows.chebwin({length}, at={abs(spec.cheb_atten_db)!r}, "
            "sym=True)"
        )
    if spec.window == "kaiser":
        return (
            f"signal.windows.kaiser({length}, beta={spec.window_param!r}, "
            "sym=True)"
        )
    return f"signal.get_window({spec.window!r}, {length}, fftbins=False)"


def _radar_redesign_call(fd: FilterDesign) -> list[str] | None:
    """Rebuild a radar design from its closed form.

    Written out in full rather than importing this package, so the generated
    module stays standalone: numpy and scipy are all it needs.
    """
    s = fd.spec

    if s.response is Response.MTI_CANCELLER:
        return [
            "# Binomial coefficients with alternating signs: an N-pulse",
            "# canceller is (N-1) cascaded single cancellers.",
            f"taps = np.array({[float(v) for v in fd.b]!r})",
            "return taps",
        ]

    chirp_rate = s.chirp_bandwidth_hz / s.pulse_width_s
    if s.down_chirp:
        chirp_rate = -chirp_rate
    lines = [
        "n = TAPS.size",
        "# Time axis centred on the pulse, so the compressed peak lands",
        "# in the middle of the filter.",
        "t = (np.arange(n) - (n - 1) / 2.0) / SAMPLE_RATE",
        f"chirp_rate = {chirp_rate!r}  # Hz per second",
        "",
        "# The matched filter is the conjugate of the transmitted chirp.",
        "taps = np.conj(np.exp(1j * np.pi * chirp_rate * t**2))",
        f"taps = taps * {_window_expression(s, 'n')}",
        "",
        "# Unit energy: the matched-filter convention, which maximises SNR.",
        "taps = taps / np.sqrt(np.sum(np.abs(taps) ** 2))",
    ]
    if s.gain != 1.0:
        lines.append(f"taps = taps * {s.gain!r}")
    lines.append("return taps")
    return lines


def _kaiser_beta(spec) -> float:
    from ..core.firdes import kaiser_beta_for_atten

    if spec.auto_order:
        return kaiser_beta_for_atten(spec.stopband_atten_db)
    return spec.window_param


def _main_block(fd: FilterDesign, name: str) -> list[str]:
    coeff = "TAPS" if fd.is_fir else "SOS"
    designer = "design_taps" if fd.is_fir else "design_sos"
    return [
        "",
        'if __name__ == "__main__":',
        "    # Verify the stored coefficients against a fresh design, then",
        "    # show the response.",
        f"    recomputed = {designer}()",
        f"    if np.allclose(recomputed, {coeff}, rtol=0, atol=1e-12):",
        f'        print("OK: stored {coeff.lower()} match a fresh design")',
        "    else:",
        "        peak = np.max(np.abs(np.asarray(recomputed).ravel()"
        f" - np.asarray({coeff}).ravel()))",
        '        print(f"WARNING: stored coefficients differ by up to {peak:.3g}")',
        "",
        f"    filt = {name}()",
        "    import matplotlib.pyplot as plt",
        "",
        (
            "    w, h = signal.freqz(TAPS, [1.0], "
            "worN=np.linspace(-SAMPLE_RATE / 2, SAMPLE_RATE / 2, 4096), "
            "fs=SAMPLE_RATE)"
            if fd.is_fir and fd.is_complex
            else "    w, h = signal."
            + ("freqz(TAPS, [1.0]" if fd.is_fir else "sosfreqz(SOS")
            + ", worN=4096, fs=SAMPLE_RATE)"
        ),
        "    fig, ax = plt.subplots(2, 1, figsize=(9, 7), sharex=True)",
        "    ax[0].plot(w, 20 * np.log10(np.maximum(np.abs(h), 1e-12)))",
        '    ax[0].set_ylabel("Magnitude (dB)")',
        "    ax[0].grid(True, alpha=0.3)",
        "    ax[1].plot(w, np.unwrap(np.angle(h)) * 180 / np.pi)",
        '    ax[1].set_ylabel("Phase (deg)")',
        '    ax[1].set_xlabel("Frequency (Hz)")',
        "    ax[1].grid(True, alpha=0.3)",
        f'    fig.suptitle("{fd.spec.name}")',
        "    plt.tight_layout()",
        "    plt.show()",
    ]
