"""Tap generators and order estimators that scipy does not provide.

The pulse-shaping responses (RRC, RC, Gaussian) are the ones an SDR user
reaches for constantly but ``scipy.signal`` has no direct equivalent of, so
they are implemented here from their closed-form impulse responses.  The
naming deliberately mirrors GNU Radio's ``gr::filter::firdes`` so that code
generated by this tool reads the same way as hand-written GNU Radio code.

Order estimation lives here too: ``firwin``/``remez``/``firls`` all take a tap
count rather than a tolerance, so something has to turn "60 dB stopband over a
25 kHz transition" into a number of taps.
"""

from __future__ import annotations

import math

import numpy as np
from scipy import signal

#: Approximate stopband attenuation a windowed (``firwin``) design can reach
#: with each window, in dB.  This is set by the window's peak sidelobe and is
#: a *hard ceiling*: adding taps narrows the transition but does not push the
#: stopband any deeper.  It is the single most common surprise in windowed
#: FIR design, so the designer warns about it explicitly.
WINDOW_MAX_ATTEN_DB: dict[str, float] = {
    "boxcar": 21.0,
    "bartlett": 26.0,
    "hann": 44.0,
    "hamming": 53.0,
    "blackman": 74.0,
    "flattop": 85.0,
    "blackmanharris": 92.0,
    "nuttall": 98.0,
}


#: Approximate transition-width constant ``K`` for each window, such that
#: ``num_taps ~= K * sample_rate / transition_width``.  It comes from the
#: window's main-lobe width (Oppenheim & Schafer's table, extended to the
#: multi-term windows), and it is what actually sets the length -- a Blackman
#: window needs roughly 1.7x the taps of a Hamming to hit the same transition
#: because its main lobe is that much wider.
WINDOW_TRANSITION_K: dict[str, float] = {
    "boxcar": 0.905,
    "bartlett": 3.05,
    "hann": 3.10,
    "hamming": 3.30,
    "blackman": 5.50,
    "blackmanharris": 7.60,
    "nuttall": 8.00,
    "flattop": 9.00,
}


def window_atten_limit(window: str) -> float | None:
    """Stopband ceiling for ``window``, or ``None`` if it has no fixed ceiling.

    Kaiser is the exception: its beta parameter trades sidelobe level against
    transition width, so it can hit any attenuation you ask for.
    """
    return WINDOW_MAX_ATTEN_DB.get(window)


def suggest_window(stopband_atten_db: float) -> str:
    """Cheapest fixed window that can reach ``stopband_atten_db``."""
    for name, limit in sorted(WINDOW_MAX_ATTEN_DB.items(), key=lambda kv: kv[1]):
        if limit >= stopband_atten_db:
            return name
    return "kaiser"


__all__ = [
    "normalise_taps",
    "WINDOW_MAX_ATTEN_DB",
    "window_atten_limit",
    "suggest_window",
    "root_raised_cosine",
    "raised_cosine",
    "gaussian",
    "ripple_to_delta",
    "estimate_fir_taps",
    "kaiser_beta_for_atten",
]


# --------------------------------------------------------------------------
# Normalisation
# --------------------------------------------------------------------------
def normalise_taps(taps: np.ndarray, mode: str = "sum", gain: float = 1.0) -> np.ndarray:
    """Scale ``taps`` according to ``mode`` and apply ``gain``.

    ``sum``     DC gain becomes ``gain`` (GNU Radio's convention).
    ``energy``  sum of squares becomes ``gain**2`` -- the right choice for a
                matched filter, where an RRC pair must compose to unit gain.
    ``peak``    largest magnitude tap becomes ``gain``.
    ``none``    only ``gain`` is applied.
    """
    taps = np.asarray(taps, dtype=float)
    if mode == "sum":
        scale = taps.sum()
    elif mode == "energy":
        scale = math.sqrt(float(np.dot(taps, taps)))
    elif mode == "peak":
        scale = float(np.max(np.abs(taps)))
    elif mode == "none":
        scale = 1.0
    else:
        raise ValueError(f"unknown normalisation {mode!r}")

    # A degenerate scale (e.g. a DC-null filter normalised by "sum") would
    # blow the taps up to infinity; leave them unscaled instead.
    if not np.isfinite(scale) or abs(scale) < 1e-20:
        scale = 1.0
    return taps * (gain / scale)


# --------------------------------------------------------------------------
# Pulse shaping
# --------------------------------------------------------------------------
def root_raised_cosine(
    sps: float,
    rolloff: float,
    span_symbols: int,
    gain: float = 1.0,
    normalisation: str = "sum",
) -> np.ndarray:
    """Root-raised-cosine taps.

    Parameters
    ----------
    sps:
        Samples per symbol (``sample_rate / symbol_rate``).
    rolloff:
        Excess-bandwidth factor alpha, in ``[0, 1]``.
    span_symbols:
        Filter length in symbol periods.  The tap count is forced odd so the
        filter is linear phase with an integer group delay.
    """
    if sps <= 0:
        raise ValueError("samples per symbol must be > 0")
    if not 0.0 <= rolloff <= 1.0:
        raise ValueError("rolloff must be in [0, 1]")

    ntaps = _odd_taps(sps, span_symbols)
    # t is in symbol periods, centred on the middle tap.
    t = (np.arange(ntaps) - (ntaps - 1) / 2.0) / sps
    a = float(rolloff)
    h = np.empty(ntaps, dtype=float)

    if a == 0.0:
        # Degenerates to a plain sinc; np.sinc already handles t == 0.
        h[:] = np.sinc(t)
        return normalise_taps(h, normalisation, gain)

    # Three analytic cases: t == 0, the removable singularity at
    # t == +/- 1/(4a), and the general term.
    at_zero = np.isclose(t, 0.0, atol=1e-12)
    at_sing = np.isclose(np.abs(t), 1.0 / (4.0 * a), atol=1e-12)
    general = ~(at_zero | at_sing)

    h[at_zero] = 1.0 + a * (4.0 / math.pi - 1.0)

    h[at_sing] = (a / math.sqrt(2.0)) * (
        (1.0 + 2.0 / math.pi) * math.sin(math.pi / (4.0 * a))
        + (1.0 - 2.0 / math.pi) * math.cos(math.pi / (4.0 * a))
    )

    tg = t[general]
    num = np.sin(math.pi * tg * (1.0 - a)) + 4.0 * a * tg * np.cos(
        math.pi * tg * (1.0 + a)
    )
    den = math.pi * tg * (1.0 - (4.0 * a * tg) ** 2)
    h[general] = num / den

    return normalise_taps(h, normalisation, gain)


def raised_cosine(
    sps: float,
    rolloff: float,
    span_symbols: int,
    gain: float = 1.0,
    normalisation: str = "sum",
) -> np.ndarray:
    """Raised-cosine (full Nyquist) taps.  Arguments match :func:`root_raised_cosine`."""
    if sps <= 0:
        raise ValueError("samples per symbol must be > 0")
    if not 0.0 <= rolloff <= 1.0:
        raise ValueError("rolloff must be in [0, 1]")

    ntaps = _odd_taps(sps, span_symbols)
    t = (np.arange(ntaps) - (ntaps - 1) / 2.0) / sps
    a = float(rolloff)

    if a == 0.0:
        return normalise_taps(np.sinc(t), normalisation, gain)

    # cos(pi a t) / (1 - (2 a t)^2) has removable singularities at
    # t = +/- 1/(2a); substitute the limit there.
    at_sing = np.isclose(np.abs(t), 1.0 / (2.0 * a), atol=1e-12)
    den = 1.0 - (2.0 * a * t) ** 2
    # Avoid a divide warning at the singular points before overwriting them.
    den = np.where(at_sing, 1.0, den)
    h = np.sinc(t) * np.cos(math.pi * a * t) / den
    h[at_sing] = (math.pi / 4.0) * np.sinc(1.0 / (2.0 * a))

    return normalise_taps(h, normalisation, gain)


def gaussian(
    sps: float,
    bt: float,
    span_symbols: int,
    gain: float = 1.0,
    normalisation: str = "sum",
) -> np.ndarray:
    """Gaussian taps parameterised by the bandwidth-time product ``bt``.

    This is the pulse shape used by GMSK/GFSK.  ``bt`` is the 3 dB bandwidth
    of the Gaussian normalised by the symbol rate.
    """
    if sps <= 0:
        raise ValueError("samples per symbol must be > 0")
    if bt <= 0:
        raise ValueError("bt must be > 0")

    ntaps = _odd_taps(sps, span_symbols)
    t = (np.arange(ntaps) - (ntaps - 1) / 2.0) / sps  # symbol periods

    # Standard relation between BT and the Gaussian's time-domain sigma.
    sigma = math.sqrt(math.log(2.0)) / (2.0 * math.pi * bt)
    h = np.exp(-0.5 * (t / sigma) ** 2)
    return normalise_taps(h, normalisation, gain)


def _odd_taps(sps: float, span_symbols: int) -> int:
    """Tap count spanning ``span_symbols``, forced odd and at least 3."""
    ntaps = int(round(sps * span_symbols))
    if ntaps % 2 == 0:
        ntaps += 1
    return max(ntaps, 3)


# --------------------------------------------------------------------------
# Order estimation
# --------------------------------------------------------------------------
#: Extra taps added to Bellanger's equiripple estimate. See its use below.
BELLANGER_MARGIN_TAPS = 4


def ripple_to_delta(passband_ripple_db: float, stopband_atten_db: float) -> tuple[float, float]:
    """Convert dB tolerances to linear deviations ``(delta_p, delta_s)``.

    ``passband_ripple_db`` is peak-to-peak ripple across the passband, which
    is the convention scipy's IIR designers use, so the two stay consistent.
    """
    r = 10.0 ** (passband_ripple_db / 20.0)
    delta_p = (r - 1.0) / (r + 1.0)
    delta_s = 10.0 ** (-stopband_atten_db / 20.0)
    return delta_p, delta_s


def kaiser_beta_for_atten(stopband_atten_db: float) -> float:
    """Kaiser's empirical beta for a given stopband attenuation."""
    a = float(stopband_atten_db)
    if a > 50.0:
        return 0.1102 * (a - 8.7)
    if a >= 21.0:
        return 0.5842 * (a - 21.0) ** 0.4 + 0.07886 * (a - 21.0)
    return 0.0


def estimate_fir_taps(
    method: str,
    sample_rate: float,
    transition_width: float,
    passband_ripple_db: float,
    stopband_atten_db: float,
    window: str | None = None,
    force_odd: bool = False,
) -> tuple[int, str]:
    """Estimate a tap count for ``method``.

    Returns ``(num_taps, explanation)``.  The explanation is surfaced in the
    GUI and in the generated code so the number is never a mystery.

    The estimators differ because the algorithms differ: a windowed design
    needs more taps than an equiripple design for the same mask, and Kaiser's
    formula is the right one for the window method precisely because it is
    derived from the window's own sidelobe behaviour.
    """
    if transition_width <= 0:
        raise ValueError("transition width must be > 0")
    nyq = sample_rate / 2.0
    if transition_width >= nyq:
        raise ValueError("transition width must be below Nyquist")

    delta_p, delta_s = ripple_to_delta(passband_ripple_db, stopband_atten_db)

    if method == "window":
        k = WINDOW_TRANSITION_K.get(window or "")
        if k is None:
            # Kaiser (and anything unrecognised): its beta absorbs the
            # attenuation requirement, so the length follows from the standard
            # Kaiser formula.  scipy takes the width normalised to Nyquist.
            ntaps, _beta = signal.kaiserord(stopband_atten_db, transition_width / nyq)
            note = (
                f"Kaiser estimate for {stopband_atten_db:.1f} dB stopband over a "
                f"{transition_width:.6g} Hz transition"
            )
        else:
            # A fixed window's length is set by its main-lobe width alone --
            # the attenuation it reaches is whatever its sidelobes allow.
            ntaps = int(math.ceil(k * sample_rate / transition_width)) + 1
            note = (
                f"main-lobe width of the {window} window (K={k:g}) over a "
                f"{transition_width:.6g} Hz transition"
            )
    elif method in ("remez", "firls"):
        # Bellanger's estimate; accurate to within a few taps for equiripple
        # designs and a reasonable starting point for least squares.
        ntaps = int(
            math.ceil(
                (2.0 / 3.0)
                * math.log10(1.0 / (10.0 * delta_p * delta_s))
                * (sample_rate / transition_width)
            )
        )
        # Bellanger is an approximation and it errs low: across band types and
        # attenuations the bare estimate misses the requested mask about a
        # third of the time, usually on passband ripple rather than stopband.
        # A few extra taps costs almost nothing and makes an automatically
        # ordered design actually meet what was asked for, which is the whole
        # point of asking for it automatically.
        ntaps += BELLANGER_MARGIN_TAPS
        note = (
            f"Bellanger estimate for {passband_ripple_db:.3g} dB ripple / "
            f"{stopband_atten_db:.1f} dB stopband over a "
            f"{transition_width:.6g} Hz transition, plus a "
            f"{BELLANGER_MARGIN_TAPS}-tap margin"
        )
    else:  # freq_sampling and anything else -- fall back to the harris rule
        ntaps = int(math.ceil(stopband_atten_db * sample_rate / (22.0 * transition_width)))
        note = (
            f"harris rule-of-thumb for {stopband_atten_db:.1f} dB stopband "
            f"over a {transition_width:.6g} Hz transition"
        )

    ntaps = max(int(ntaps), 3)
    if force_odd and ntaps % 2 == 0:
        ntaps += 1
    # Guard against a pathologically narrow transition producing millions of
    # taps and freezing the GUI.
    ntaps = min(ntaps, 32_001)
    return ntaps, note
